hell_mail/urls.py
from django.urls import path
from . import views


app_name = "hell_mail"

urlpatterns = [
    path("", views.index, name ="index"),
    path("complete", views.complete, name ="complete"),
]

#path("hell_mail_form/complete/mail/", views.SendMail, name = "sendmail")

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hell_mail.urls")),
]

hell_mail/models.py
from django.conf import settings
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=200)
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField(default=0)
    birthday = models.DateField()

    def __str__(self):
        return '<Friend:id=' + str(self.id) + ',' + self.name + "(" + str(self.age) + ")>"

# Create your models here.

hell_mail/forms.py
from django import forms

class HellmailForm( forms.Form):
    subject = forms.CharField( label= "相手の名前", widget=forms.TextInput(attrs={"autocomplete":"off"}))
    sender = forms.EmailField( label = "あなたのメールアドレス", widget=forms.TextInput(attrs={"autocomplete":"off"}))

hell_mail/views.py
from django.shortcuts import render, redirect
from .forms import HellmailForm
from django.core.mail import BadHeaderError, send_mail
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect


def index(request):

    if request.method == "POST":
        form = HellmailForm(request.POST)

        if form.is_valid():
            Subject = "地獄通信"
            human = form.cleaned_data["subject"]
            message = "対象者は" +  human + "。\n\nこのメールに「はい」と返信すれば、私と正式に契約を交わしたことになる。怨みの相手は速やかに地獄へ流されるわ。\n\n\nただし、怨みを晴らしたら、あなた自身にも代償を支払ってもらう。\n\n\n「人を呪わば穴二つ」\n\n\n-----後はあなたが決める事よ。\n\n\n\n閻魔あい"
            sender = [ settings.EMAIL_HOST_USER ]
            recipients = []
            recipients.append(form.cleaned_data["sender"])
            try:
                send_mail(Subject, message, sender, recipients)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            return redirect("hell_mail:complete")
    
    else:
        form = HellmailForm()

    return render(request, "hell_mail/index.html", {"form": form})

def complete(request):
    return render(request, "hell_mail/complete.html")

hell_mail/templates/hell_mail/complete.html
{% extends 'hell_mail/index.html' %}
{% load static %}

{% block body_block %}
<center>
    <h1 class="word">人を呪わば穴二つ</h1>
    <img src="{% static 'hell_mail\candle.jpg' %}" width="100" height="100">
    <h2 class="send"> メールが届いています</h2>
</center>
{%endblock%}

hell_mail/templates/hell_mail/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" type = "text/css" href="{% static 'hell_mail/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap" rel="stylesheet">
</head>
<body class="container text-white">
    {% block body_block %}
    <center>
        <h1 class="font-large">地獄通信</h1>
        <h2 class="font-small">あなたの怨み、晴らします。</h1><hr>
        <br>
    <div class="form-row mx-auto" style="width: 200px;">
        <form action="{% url 'hell_mail:index' %}" method = "post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-dark my-0 text-white" value="送信">
        </form>
    </div>
    </center>
    {% endblock %}
</body>
</html>